### ISSUE TITLE
PHP Fatal error: Call-time pass-by-reference in PHP 5.4

### ISSUE THREAD

**Issue by mhawksey** [jammycakes/comment-timeout#1]
My host recently upgraded to PHP 5.4 and this killed my wp-admin with a PHP Fatal error: Call-time pass-by-reference. Using http://stackoverflow.com/questions/8971261/php-5-4-call-time-pass-by-reference-easy-fix-available I was able to fix by replacing `&$this` with `$this` 

[Fantastic plugin!]

**Comment by jammycakes** [comment]
Thanks -- are you able to submit me a pull request for this?

**Comment by mhawksey** [comment]
pull request submitted

**Comment by jammycakes** [comment]
Thanks -- released in version 2.4.1.
